language: node_js
node_js:
  - 10.15.1
cache:
  directories:
    - node_modules
install: yarn
stages:
  - install_dependencies
  - test
  - build
  - release
    if: branch = master
jobs:
  include:
    - stage: install_dependencies
      script: yarn -s --no-progress --frozen-lockfile
    - stage: test
      script: yarn test --coverage && cat ./coverage/lcov.info | yarn codacy-coverage && yarn codecov
    - stage: build
      script: yarn build && yarn ts:defs
    - stage: release
      script: yarn release
